/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Orla {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "AgentGraph".
 */
export interface AgentGraph {
  id: string;
  name: string;
  description: string;
  nodes: Node[];
  edges: Edge[];
  /**
   * Requests the graph should handle well. Measuring a change runs the graph over the sample, so the sample decides what a measured result means.
   */
  sample: string[];
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Node".
 */
export interface Node {
  id: string;
  name: string;
  position: Position;
  notes: string;
  config:
    | InputConfig
    | OutputConfig
    | LLMConfig
    | ToolConfig
    | ReactConfig
    | RouterConfig
    | SubagentConfig
    | JudgeConfig
    | ApproveConfig;
}
/**
 * Where the node sits on the canvas, in canvas coordinates.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Position".
 */
export interface Position {
  x: number;
  y: number;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "InputConfig".
 */
export interface InputConfig {
  kind: "input";
  description: string;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "OutputConfig".
 */
export interface OutputConfig {
  kind: "output";
  description: string;
}
/**
 * A single model call. One prompt in, one response out.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "LLMConfig".
 */
export interface LLMConfig {
  kind: "llm";
  stage: string;
  model: string;
  instructions: string;
  prompt: string;
}
/**
 * A deterministic call into the tool catalog. No model involved.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "ToolConfig".
 */
export interface ToolConfig {
  kind: "tool";
  tool: string;
  arguments: {
    [k: string]: string;
  };
}
/**
 * A reason-and-act loop. The model calls tools until it answers or
 * the iteration cap stops it.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "ReactConfig".
 */
export interface ReactConfig {
  kind: "react";
  stage: string;
  model: string;
  instructions: string;
  prompt: string;
  tools: string[];
  max_iterations: number;
}
/**
 * A classifier that picks one outgoing branch. Nodes on the
 * branches the router does not pick are skipped for that run.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "RouterConfig".
 */
export interface RouterConfig {
  kind: "router";
  stage: string;
  model: string;
  question: string;
  prompt: string;
  routes: Route[];
}
/**
 * One labelled branch out of a router. The label matches the label
 * on the outgoing edge that carries it.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Route".
 */
export interface Route {
  label: string;
  description: string;
}
/**
 * A call into another workflow in the same workspace. Saving a workflow
 * puts it in the palette of every other one, which is how a system gets
 * assembled out of parts that were each built alone.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "SubagentConfig".
 */
export interface SubagentConfig {
  kind: "subagent";
  graph_id: string;
  prompt: string;
}
/**
 * A judge on the stage feeding it. The judge reads that stage's output
 * against the criteria. A pass lets the output through untouched. A fail
 * sends the feedback back to the stage, which answers again, up to
 * max_rounds times. Downstream stages read the version that passed, or the
 * last attempt when nothing did.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "JudgeConfig".
 */
export interface JudgeConfig {
  kind: "judge";
  stage: string;
  model: string;
  criteria: string;
  max_rounds: number;
}
/**
 * A pause for a person. The run shows what the stage feeding it produced
 * and waits. Approving lets it through. Sending it back with a note asks the
 * Prompt or Agent behind it to answer again, up to max_rounds times.
 * Declining stops everything downstream.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "ApproveConfig".
 */
export interface ApproveConfig {
  kind: "approve";
  question: string;
  max_rounds: number;
}
/**
 * A data dependency. The target reads the source's output through
 * a template reference to the source node's name. label carries the
 * route name when the source is a router.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Edge".
 */
export interface Edge {
  id: string;
  source: string;
  target: string;
  label: string;
}
/**
 * Progress from a compile. Writing the module takes long enough that
 * silence reads as a hang, and the checks it runs are worth watching.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "CompileEvent".
 */
export interface CompileEvent {
  type: "writing" | "checking" | "rejected" | "done" | "error";
  attempt: number;
  problems: string[];
  result: CompileResult | null;
  text: string;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "CompileResult".
 */
export interface CompileResult {
  source: string;
  notes: string;
  attempts: number;
  problems: string[];
  ok: boolean;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Decision".
 */
export interface Decision {
  approved: boolean;
  note: string;
}
/**
 * Per node and total cost for one request through the graph. A node
 * behind a router is weighted by an even split across the router's
 * routes, since a static estimate has no traffic to learn a real split
 * from.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "GraphEstimate".
 */
export interface GraphEstimate {
  nodes: NodeEstimate[];
  usd: number;
  input_tokens: number;
  output_tokens: number;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "NodeEstimate".
 */
export interface NodeEstimate {
  node_id: string;
  name: string;
  model: string;
  calls: number;
  input_tokens: number;
  output_tokens: number;
  usd: number;
}
/**
 * Whether the server can call a model, and the workspace defaults the
 * settings page shows.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Health".
 */
export interface Health {
  ok: boolean;
  model_credentials: boolean;
  compiler_model: string;
  judge_model: string;
  assistant_model: string;
  measure_budget_usd: number;
  workspace: string;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "MeasureEvent".
 */
export interface MeasureEvent {
  type: "plan" | "run_done" | "baseline_done" | "patch_done" | "done" | "error";
  plan: MeasurePlan | null;
  label: string;
  request: string;
  baseline: Measurement | null;
  patch: PatchMeasurement | null;
  spent_usd: number;
  text: string;
}
/**
 * What the run is about to do and what it is about to spend.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "MeasurePlan".
 */
export interface MeasurePlan {
  sample_size: number;
  candidates: number;
  graph_runs: number;
  judgements: number;
  projected_usd: number;
  budget_usd: number;
}
/**
 * What a version of the graph did across the whole sample. usd and ms
 * are means over the runs that finished, and spread is the gap between
 * the cheapest and the dearest run, which is what says how much to trust
 * the mean.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Measurement".
 */
export interface Measurement {
  runs: SampleRun[];
  usd: number;
  ms: number;
  usd_spread: number;
  n: number;
  failures: number;
}
/**
 * One request through one version of the graph.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "SampleRun".
 */
export interface SampleRun {
  request: string;
  output: string;
  usd: number;
  ms: number;
  input_tokens: number;
  output_tokens: number;
  error: string;
}
/**
 * One candidate, measured.
 *
 * Every delta is paired. Both versions ran the same requests, and only the
 * requests both versions completed count toward a delta, so a candidate that
 * crashed on the expensive request cannot bank the cost it never paid. A
 * candidate that completed nothing reports an error and no delta at all,
 * because a broken graph is the cheapest graph there is.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "PatchMeasurement".
 */
export interface PatchMeasurement {
  patch_id: string;
  title: string;
  candidate: Measurement;
  baseline_usd: number;
  usd_delta: number;
  ms_delta: number;
  paired: number;
  verdicts: Verdict[];
  wins: number;
  losses: number;
  ties: number;
  error: string;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Verdict".
 */
export interface Verdict {
  request: string;
  winner: "baseline" | "candidate" | "tie";
  reason: string;
  agreed: boolean;
}
/**
 * One inference endpoint a stage can be bound to. quality_prior is
 * the operator's own belief about how strong the model is, on a zero
 * to one scale, and it is what the optimizer trades against cost.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "ModelSpec".
 */
export interface ModelSpec {
  id: string;
  provider: "bedrock-mantle" | "bedrock-runtime" | "anthropic" | "openai" | "ollama";
  model: string;
  label: string;
  endpoint: string;
  api_key_var: string;
  input_usd_per_mtok: number;
  output_usd_per_mtok: number;
  quality_prior: number;
  tools: boolean;
  structured: boolean;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "OptimizeResult".
 */
export interface OptimizeResult {
  summary: string;
  baseline_usd: number;
  patches: PricedPatch[];
  ok: boolean;
  error: string;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "PricedPatch".
 */
export interface PricedPatch {
  patch: Patch;
  usd_delta: number;
  applies: boolean;
  problems: string[];
}
/**
 * One proposed change. node_id names the node the operation acts
 * on, and the fields a given operation reads are the only ones it
 * needs.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Patch".
 */
export interface Patch {
  id: string;
  /**
   * A short imperative summary, for example 'Serve clarify with the cheapest model'.
   */
  title: string;
  /**
   * Two sentences at most on why the change helps.
   */
  rationale: string;
  op:
    | "set_model"
    | "set_stage"
    | "set_instructions"
    | "set_prompt"
    | "set_max_iterations"
    | "remove_node"
    | "insert_llm_after";
  node_id: string;
  model: string;
  stage: string;
  instructions: string;
  prompt: string;
  max_iterations: number;
  /**
   * For insert_llm_after, the new node's name.
   */
  name: string;
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "PatchResponse".
 */
export interface PatchResponse {
  graph: AgentGraph;
  diff: {
    [k: string]: string[];
  };
  estimate: GraphEstimate;
}
/**
 * One thing wrong with a graph. node_id is empty when the problem
 * belongs to the graph as a whole.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "Problem".
 */
export interface Problem {
  severity: "error" | "warning";
  message: string;
  node_id: string;
}
/**
 * One thing that happened during a run. The canvas lights a node on
 * node_start and fills it in on node_done. An approval event carries the
 * token a person answers against.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "RunEvent".
 */
export interface RunEvent {
  type:
    | "run_start"
    | "node_start"
    | "node_done"
    | "node_skipped"
    | "approval"
    | "run_done"
    | "run_error";
  token: string;
  node_id: string;
  name: string;
  kind: string;
  stage: string;
  model: string;
  text: string;
  route: string;
  ms: number;
  usd: number;
  input_tokens: number;
  output_tokens: number;
  depth: number;
  graph_id: string;
}
/**
 * One entry in the tool catalog. A tool has one name, the name of the
 * function it calls, so nothing on screen shows a second one. The prototype
 * ships offline implementations so a graph runs with no credentials beyond
 * the model key.
 *
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "ToolSpec".
 */
export interface ToolSpec {
  id: string;
  description: string;
  parameters: string[];
}
/**
 * This interface was referenced by `Orla`'s JSON-Schema
 * via the `definition` "ValidateResponse".
 */
export interface ValidateResponse {
  problems: Problem[];
  estimate: GraphEstimate;
}
